// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Case6Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void case6() {
    // Test name: case6
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:9000/");
    // 2 | setWindowSize | 1440x877 | 
    driver.manage().window().setSize(new Dimension(1440, 877));
    // 3 | click | id=lifePoint | 
    driver.findElement(By.id("lifePoint")).click();
    // 4 | type | id=lifePoint | 10
    driver.findElement(By.id("lifePoint")).sendKeys("10");
    // 5 | click | id=startButton | 
    driver.findElement(By.id("startButton")).click();
    // 6 | click | id=plusPlayer1 | 
    driver.findElement(By.id("plusPlayer1")).click();
    // 7 | click | css=.column2:nth-child(1) .button | 
    driver.findElement(By.cssSelector(".column2:nth-child(1) .button")).click();
    // 8 | click | id=players | 
    driver.findElement(By.id("players")).click();
    // 9 | select | id=players | label=3
    {
      WebElement dropdown = driver.findElement(By.id("players"));
      dropdown.findElement(By.xpath("//option[. = '3']")).click();
    }
    // 10 | click | id=lifePoint | 
    driver.findElement(By.id("lifePoint")).click();
    // 11 | type | id=lifePoint | 100
    driver.findElement(By.id("lifePoint")).sendKeys("100");
    // 12 | click | id=startButton | 
    driver.findElement(By.id("startButton")).click();
    // 13 | click | id=plusPlayer1 | 
    driver.findElement(By.id("plusPlayer1")).click();
    // 14 | click | css=.column2:nth-child(1) .button | 
    driver.findElement(By.cssSelector(".column2:nth-child(1) .button")).click();
    // 15 | click | id=lifePoint | 
    driver.findElement(By.id("lifePoint")).click();
    // 16 | type | id=lifePoint | 50
    driver.findElement(By.id("lifePoint")).sendKeys("50");
    // 17 | click | id=startButton | 
    driver.findElement(By.id("startButton")).click();
    // 18 | click | css=.column:nth-child(1) .lifeBox | 
    driver.findElement(By.cssSelector(".column:nth-child(1) .lifeBox")).click();
    // 19 | click | css=.column:nth-child(1) .lifeBox | 
    driver.findElement(By.cssSelector(".column:nth-child(1) .lifeBox")).click();
    // 20 | doubleClick | css=.column:nth-child(1) .lifeBox | 
    {
      WebElement element = driver.findElement(By.cssSelector(".column:nth-child(1) .lifeBox"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 21 | click | id=plusPlayer1 | 
    driver.findElement(By.id("plusPlayer1")).click();
    // 22 | click | id=plusPlayer1 | 
    driver.findElement(By.id("plusPlayer1")).click();
    // 23 | doubleClick | id=plusPlayer1 | 
    {
      WebElement element = driver.findElement(By.id("plusPlayer1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 24 | click | css=.column2:nth-child(1) .button | 
    driver.findElement(By.cssSelector(".column2:nth-child(1) .button")).click();
  }
}
