package mandatory.test;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Case1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  DataProvider dataProvider = new DataProvider();
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void case1() {

    for (int i = 0; i < dataProvider.amountOfPlayers.size(); i++) {

      // Test name: case1
      // Step # | name | target | value
      // 1 | open | / |
      driver.get("http://localhost:9000/");
      // 2 | setWindowSize | 1440x877 |
      driver.manage().window().setSize(new Dimension(1440, 877));
      // 3 | click | id=players |
      driver.findElement(By.id("players")).click();
      // 4 | select | id=players | label=3
      {
        WebElement dropdown = driver.findElement(By.id("players"));
        dropdown.findElement(By.xpath("//option[. ='" + dataProvider.amountOfPlayers.get(i) + "']")).click();
      }
      // 5 | click | id=lifePoint |
      driver.findElement(By.id("lifePoint")).click();
      // 6 | type | id=lifePoint | 50
      driver.findElement(By.id("lifePoint")).sendKeys("50");
      // 7 | click | id=startButton |
      driver.findElement(By.id("startButton")).click();

    }

  }

  @Test
  public void case2() {

    for (int i = 0; i < dataProvider.startingLife.size(); i++) {

      // Test name: case1
      // Step # | name | target | value
      // 1 | open | / |
      driver.get("http://localhost:9000/");
      // 2 | setWindowSize | 1440x877 |
      driver.manage().window().setSize(new Dimension(1440, 877));
      // 3 | click | id=players |
      driver.findElement(By.id("players")).click();
      // 4 | select | id=players | label=3
      {
        WebElement dropdown = driver.findElement(By.id("players"));
        dropdown.findElement(By.xpath("//option[. ='3']")).click();
      }
      // 5 | click | id=lifePoint |
      driver.findElement(By.id("lifePoint")).click();
      // 6 | type | id=lifePoint | 50
      driver.findElement(By.id("lifePoint")).sendKeys(dataProvider.startingLife.get(i).toString());
      // 7 | click | id=startButton |
      driver.findElement(By.id("startButton")).click();

    }

  }


  @Test
  public void case3() throws InterruptedException {
    // Test name: case2
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:9000/");
    // 2 | setWindowSize | 1440x877 |
    driver.manage().window().setSize(new Dimension(1440, 877));
    // 3 | click | id=players |
    driver.findElement(By.id("players")).click();
    // 4 | select | id=players | label=3
    {
      WebElement dropdown = driver.findElement(By.id("players"));
      dropdown.findElement(By.xpath("//option[. = '3']")).click();
    }
    // 5 | click | id=lifePoint |
    driver.findElement(By.id("lifePoint")).click();
    // 6 | type | id=lifePoint | 30
    driver.findElement(By.id("lifePoint")).sendKeys("30");
    // 7 | click | id=startButton |
    driver.findElement(By.id("startButton")).click();
    Thread.sleep(2000);
    // 8 | click | id=plusPlayer1 |
    driver.findElement(By.id("plusPlayer1")).click();
    // 9 | click | id=plusPlayer1 |
    driver.findElement(By.id("plusPlayer1")).click();
    // 10 | click | id=plusPlayer1 |
    driver.findElement(By.id("plusPlayer1")).click();
  }
}
