// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LC3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lC3() {
    // Test name: LC_3
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:9000/");
    // 2 | setWindowSize | 1440x877 | 
    driver.manage().window().setSize(new Dimension(1440, 877));
    // 3 | click | id=players | 
    driver.findElement(By.id("players")).click();
    // 4 | select | id=players | label=3
    {
      WebElement dropdown = driver.findElement(By.id("players"));
      dropdown.findElement(By.xpath("//option[. = '3']")).click();
    }
    // 5 | click | id=lifePoint | 
    driver.findElement(By.id("lifePoint")).click();
    // 6 | type | id=lifePoint | 60
    driver.findElement(By.id("lifePoint")).sendKeys("60");
    // 7 | click | id=startButton | 
    driver.findElement(By.id("startButton")).click();
    // 8 | click | css=#editBtn1 > .fa | 
    driver.findElement(By.cssSelector("#editBtn1 > .fa")).click();
    // 9 | click | css=.column:nth-child(1) > .center:nth-child(1) | 
    driver.findElement(By.cssSelector(".column:nth-child(1) > .center:nth-child(1)")).click();
    // 10 | type | id=playerInput1 | John Johnson
    driver.findElement(By.id("playerInput1")).sendKeys("John Johnson");
    // 11 | click | css=#okBtn1 > .fa | 
    driver.findElement(By.cssSelector("#okBtn1 > .fa")).click();
    // 12 | click | css=.column2:nth-child(1) .button | 
    driver.findElement(By.cssSelector(".column2:nth-child(1) .button")).click();
  }
}
